// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrdhdbghsmfvxaidxenv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFyZGhkYmdoc21mdnhhaWR4ZW52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMzg2NDQsImV4cCI6MjA3MjkxNDY0NH0.TeogxbAosNmFkAb_fTP5K8ZDEW3CskoquHsjXzKAaMw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});